apiVersion: v1
entries:
  service-creator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-02T00:01:23.927438+02:00"
    description: A Helm chart for Kubernetes
    digest: c3241ce1dae1e8b56d23cc47915f41340f015acaf5d409668d3411de4808f866
    name: service-creator
    type: application
    urls:
    - creator/service-creator-0.1.0.tgz
    version: 0.1.0
  service-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-02T00:01:23.927865+02:00"
    description: A Helm chart for Kubernetes
    digest: dc3b9c7e55c1dcd7520412175d826a1e10f4b44653c35b4b053dc7c98a738399
    name: service-operator
    type: application
    urls:
    - operator/service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-02T00:01:23.926552+02:00"
